name: Build The Application

on: push

jobs:
  build:
    name: Build app
    runs-on: ubuntu-latest
    steps:
      - name: Pull Code
        uses: actions/checkout@v2
      - name: Build dotnet app
        run: dotnet build
      - name: Verify dotnet build
        run: ls TrickingLibrary.Api/ -R